/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-12-02 00:13:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.bills;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class allbill_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1634288757134L));
    _jspx_dependants.put("/WEB-INF/views/layouts/user/taglib.jsp", Long.valueOf(1635785058425L));
    _jspx_dependants.put("jar:file:/C:/Users/ADMIN/Desktop/SecondYear/EcommerceSellingBook/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TikiShop/WEB-INF/lib/spring-webmvc-5.2.2.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1575352110000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.2.2.RELEASE.jar", Long.valueOf(1634210641014L));
    _jspx_dependants.put("jar:file:/C:/Users/ADMIN/Desktop/SecondYear/EcommerceSellingBook/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TikiShop/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425967870000L));
    _jspx_dependants.put("jar:file:/C:/Users/ADMIN/Desktop/SecondYear/EcommerceSellingBook/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TikiShop/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425967870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Bills</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"span12\">\r\n");
      out.write("			<ul class=\"breadcrumb\">\r\n");
      out.write("				<li><a href=\"index.html\">Home</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("				<li class=\"active\">Bills</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"well well-small\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					Bill <small class=\"pull-right\"> 4 bill(s) </small>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<hr class=\"soften\" />\r\n");
      out.write("\r\n");
      out.write("				<table class=\"table table-bordered table-condensed\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>User</th>\r\n");
      out.write("							<th>Phone</th>\r\n");
      out.write("							<th>Full name</th>\r\n");
      out.write("							<th>Address</th>\r\n");
      out.write("							<th>Total</th>\r\n");
      out.write("							<th>Quantity</th>\r\n");
      out.write("							<th>Note</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>vietngaqhh@gmail.com</td>\r\n");
      out.write("								<td>+7921922314</td>\r\n");
      out.write("								<td>Jeremie Nguyen</td>\r\n");
      out.write("								<td>31, Ba Trieu Street, Hue City</td>\r\n");
      out.write("								<td>$18.98</td>\r\n");
      out.write("								<td>2</td>\r\n");
      out.write("								<td>Delivery on Sunday</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>shin22@gmail.com</td>\r\n");
      out.write("								<td>+7932415661</td>\r\n");
      out.write("								<td>John Smith</td>\r\n");
      out.write("								<td>29, Hai Ba Trung Street, Hue City</td>\r\n");
      out.write("								<td>$20.22</td>\r\n");
      out.write("								<td>3</td>\r\n");
      out.write("								<td>I want to receive it next Monday</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>virtax1999@gmail.com</td>\r\n");
      out.write("								<td>+7931212512</td>\r\n");
      out.write("								<td>Thanh Binh</td>\r\n");
      out.write("								<td>41, Le Loi Street, Hue City</td>\r\n");
      out.write("								<td>$10.20</td>\r\n");
      out.write("								<td>1</td>\r\n");
      out.write("								<td>Any day</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							\r\n");
      out.write("							<tr>\r\n");
      out.write("								<td>nhattran09@gmail.com</td>\r\n");
      out.write("								<td>+79219426101</td>\r\n");
      out.write("								<td>Nhat Tran</td>\r\n");
      out.write("								<td>09, Nguyen Dinh Chieu Street, Hue City</td>\r\n");
      out.write("								<td>$99.99</td>\r\n");
      out.write("								<td>5</td>\r\n");
      out.write("								<td>Any day</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<content tag=\"script\"> <script>\r\n");
      out.write("		$(\".edit-cart\").on(\"click\", function() {\r\n");
      out.write("			var id = $(this).data(\"id\");\r\n");
      out.write("			var quantity = $(\"#quantity-cart-\" + id).val();\r\n");
      out.write("			window.location = \"EditCart/\" + id + \"/\" + quantity;\r\n");
      out.write("		})\r\n");
      out.write("	</script> </content>\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
